### ISSUE TITLE
This package has a minimum iOS version of 13.0

### ISSUE THREAD

**Issue by BobbyRohweder** [adam-fowler/swift-srp#1]
I am attempting to use this code in a project with a base version of 12.0

What needs a minimum version of 13.0?

**Comment by adam-fowler** [comment]
@BobbyRohweder the package is dependent on [swift-crypto](https://github.com/apple/swift-crypto) which on iOS is dependent on the CryptoKit framework which requires iOS 13.0

**Comment by adam-fowler** [comment]
closing this as there isn't anything that can be done
