### ISSUE TITLE
the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by Dadoum** [adam-fowler/swift-srp#3]
In swift-srp/Sources/SRP/srp.swift:34:19, the expression is too long to be resolved by the compiler.
Possible fix: make it multi step

**Comment by adam-fowler** [comment]
> In swift-srp/Sources/SRP/srp.swift:34:19, the expression is too long to be resolved by the compiler.
> 
> Possible fix: make it multi step

What version of swift are you compiling with?

**Comment by Dadoum** [comment]
swift 5.3

**Comment by Dadoum** [comment]
On 5.2.5 it works, but on 5.3 it does not.

**Comment by adam-fowler** [comment]
Fixed! Also added swift nightly build to CI to ensure this doesn't happen again
