### ISSUE TITLE
Can this be used for SRP authentication with AWS

### ISSUE THREAD

**Issue by nicholascross** [adam-fowler/swift-srp#5]
I was able to get SRP auth working with AWS using the [SRP class](https://github.com/adam-fowler/aws-cognito-authentication-kit/blob/main/Sources/AWSCognitoAuthenticationSRP/Authenticatable%2BSRP.swift) you wrote.

However I struggled for hours trying to use this package without success.  I was wondering if you could tell me; am I barking up the wrong tree in thinking this library should also work with Cognito SRP?  I think it is more likely I am just doing it wrong.

I will go with your other implementation for now so feel free to close this without remorse if you don't have time to respond 😄

**Comment by adam-fowler** [comment]
No it can't. It appears AWS has some minor alterations to the SRP calculations which are non-standard.
