### ISSUE TITLE
struct SRPKeyPair internal to open

### ISSUE THREAD

**Issue by GreenSnakeLinux** [adam-fowler/swift-srp#8]
Hello

I need to put my own private and public keys in the struct SRPKeyPair 
But unfortunately I cannot use it outside the module, it is missing the open keyword
Can you add it ?

thanks

**Comment by adam-fowler** [comment]
Can I ask why you need to do this? Is it because you are generating your own keys?

**Comment by GreenSnakeLinux** [comment]
Yes i need to generate my owns, i need to use them after srp process

**Comment by adam-fowler** [comment]
I completely forgot someone already did a PR for this change, but I didn't do a release. If you get v0.5.0 you should have a public `init` for SRPKeyPair
