### ISSUE TITLE
Validated this library against tssrp6a

### ISSUE THREAD

**Issue by Xavier59** [adam-fowler/swift-srp#9]
Thank you for the library @adam-fowler ! :)

I wanted to let future users know that this module  is compatible with [tssrp6a](https://github.com/midonet/tssrp6a/) as I have tested it today.
Note : It is necessary to use `calculateSimpleClientProof`. Do not use `calculateClientProof` or it won't work.

**Comment by adam-fowler** [comment]
cheers, did you mean you should use `calculateClientProof`?

**Comment by Xavier59** [comment]
Edited my post to correct this mistake

**Comment by Xavier59** [comment]
Also, the default identity calculation of `tssrp6a` does not contain the username, while this library does.
There is actually an [issue & PR](https://github.com/midonet/tssrp6a/pull/88) open on `tssrp6a` to add the username in identity so that it conforms better to srp 6a. However as of today, it is not yet the case.
Server side on `tssrp6a`, I had to add the following : 

```ts
class SRP6aRoutines extends SRPRoutines {
    public computeIdentityHash(I: string, P: string): Promise<ArrayBuffer> {
        return this.hash(new TextEncoder().encode(`${I}:${P}`).buffer)
    }
}
```

In the `README.md` of `swift-srp`, `SHA256` is used. `tssrp6a` default to `SHA512`. If you use this 2 libraries, make sure to have the same hashing algorithm set.
